id: system_settings_system_wide_preferences_configure
title: "Require Administrator Password to Modify System-Wide Preferences"
discussion: |
  The system _MUST_ be configured to require an administrator password in order to modify the system-wide preferences in System Settings. 

  Some Preference Panes in System Settings contain settings that affect the entire system. Requiring a password to unlock these system-wide settings reduces the risk of a non-authorized user modifying system configurations.
check: |
  authDBs=("system.preferences" "system.preferences.energysaver" "system.preferences.network" "system.preferences.printing" "system.preferences.sharing" "system.preferences.softwareupdate" "system.preferences.startupdisk" "system.preferences.timemachine")
  result="1"
  for section in ${authDBs[@]}; do
    if [[ $(/usr/bin/security -q authorizationdb read "$section" | /usr/bin/xmllint -xpath 'name(//*[contains(text(), "shared")]/following-sibling::*[1])' -) != "false" ]]; then
      result="0"
    fi
  done
  echo $result
result:
  integer: 1
fix: |
  [source,bash]
  ----
  authDBs=("system.preferences" "system.preferences.energysaver" "system.preferences.network" "system.preferences.printing" "system.preferences.sharing" "system.preferences.softwareupdate" "system.preferences.startupdisk" "system.preferences.timemachine")

  for section in ${authDBs[@]}; do
  /usr/bin/security -q authorizationdb read "$section" > "/tmp/$section.plist"
  key_value=$(/usr/libexec/PlistBuddy -c "Print :shared" "/tmp/$section.plist" 2>&1)
  	if [[ "$key_value" == *"Does Not Exist"* ]]; then
    		/usr/libexec/PlistBuddy -c "Add :shared bool false" "/tmp/$section.plist"
  	else
    		/usr/libexec/PlistBuddy -c "Set :shared false" "/tmp/$section.plist"
  	fi
    	/usr/bin/security -q authorizationdb write "$section" < "/tmp/$section.plist"
  done
  ----
references:
  cce:
    - CCE-91986-0
  800-53r5:
    - AC-6
    - AC-6(2)
    - AC-6(1)
  800-53r4:
    - AC-6
    - AC-6(1)
    - AC-6(2)
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.5
    - 3.1.6
  cis:
    benchmark:
      - 2.6.7 (level 1)
    controls v8:
      - 4.1
macOS:
  - "13.0"
tags:
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171 
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: "medium"
mobileconfig: false
mobileconfig_info: