id: system_settings_guest_account_disable
title: "Disable the Guest Account"
discussion: |
  Guest access _MUST_ be disabled. 
  
  Turning off guest access prevents anonymous users from accessing files.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\
  .objectForKey('DisableGuestAccount').js
  EOS
result:
  string: "true"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91953-0
  cci:
    - N/A
  800-53r5:
    - AC-2
    - AC-2(9)
  800-53r4:
    - AC-2
    - AC-2(9)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.5.1
    - 3.5.2
  cis:
    benchmark: 
      - 2.12.1 (level 1)
    controls v8: 
      - 5.2
      - 6.2
      - 6.8
macOS:
  - "13.0"
tags:
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171 
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: "high"
mobileconfig: true
mobileconfig_info:
  com.apple.MCX:
    DisableGuestAccount: true