id: system_settings_hot_corners_disable
title: "Disable Hot Corners"
discussion: |
  Hot corners _MUST_ be disabled. 

  The information system conceals, via the session lock, information previously visible on the display with a publicly viewable image. Although hot comers can be used to initiate a session lock or to launch useful applications, they can also be configured to disable an automatic session lock from initiating. Such a configuration introduces the risk that a user might forget to manually lock the screen before stepping away from the computer.
check: |
  /usr/bin/profiles -P -o stdout | /usr/bin/grep -Ec '"wvous-bl-corner" = 0|"wvous-br-corner" = 0|"wvous-tl-corner" = 0|"wvous-tr-corner" = 0'
result:
  integer: 4
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91954-8
  cci: 
    - N/A
  800-53r5:
    - AC-11(1)
  800-53r4: 
    - AC-11(1)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.10
macOS:
  - "13.0"
tags:
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171 
  - cnssi-1253
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.ManagedClient.preferences:
    com.apple.dock:
      wvous-bl-corner: 0
      wvous-br-corner: 0
      wvous-tr-corner: 0
      wvous-tl-corner: 0
