id: system_settings_siri_disable
title: "Disable Siri"
discussion: |
  Support for Siri is non-essential and _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.ironwood.support')\
  .objectForKey('Ironwood Allowed').js
  EOS
result:
  string: "false"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91976-1
  cci: 
    - N/A
  800-53r5:
    - AC-20
    - CM-7
    - CM-7(1)
    - SC-7(10)    
  800-53r4: 
    - CM-7
    - CM-7(1)
    - AC-20
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.20
    - 3.4.6
  cis:
    benchmark:
      - N/A
    controls v8:
      - 4.1
      - 4.8
macOS:
  - "13.0"
tags:
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171 
  - cnssi-1253
  - cisv8
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.ironwood.support:
    "Ironwood Allowed": false
