id: system_settings_screen_sharing_disable
title: "Disable Screen Sharing and Apple Remote Desktop"
discussion: |
  Support for both Screen Sharing and Apple Remote Desktop (ARD) is non-essential and _MUST_ be disabled.
  
  The information system _MUST_ be configured to provide only essential capabilities. Disabling screen sharing and ARD helps prevent the unauthorized connection of devices, the unauthorized transfer of information, and unauthorized tunneling.
check: |
  /bin/launchctl print-disabled system | /usr/bin/grep -c '"com.apple.screensharing" => disabled'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /bin/launchctl disable system/com.apple.screensharing
  ----
  NOTE - This will apply to the whole system
references:
  cce:
    - CCE-91972-0
  cci: 
    - N/A
  800-53r5:
    - AC-3
    - AC-17
  800-53r4:
    - AC-3
    - AC-17
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.1
    - 3.1.2
  cis:
    benchmark:
      - 2.3.3.2 (level 1)
    controls v8:
      - 4.1
      - 4.8
macOS:
  - "13.0"
tags:
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171 
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: "medium"
mobileconfig: false
mobileconfig_info: