id: system_settings_remote_management_disable
title: "Disable Remote Management"
discussion: |
  Remote Management _MUST_ be disabled. 
check: |
  /usr/libexec/mdmclient QuerySecurityInfo | /usr/bin/grep -c "RemoteDesktopEnabled = 0"
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop
  ----
references:
  cce:
    - CCE-91971-2
  cci: 
    - N/A
  800-53r5:
    - CM-7
    - CM-7(1)
  800-53r4: 
    - CM-7
    - CM-7(1)
  srg:
    - N/A
  disa_stig: 
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark: 
      - 2.3.3.6 (level 1)
    controls v8:
      - 4.1
      - 4.8
      - 5.4
macOS:
  - "13.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: