id: os_config_profile_ui_install_disable
title: "Disable Installation of Configuration Profiles through the User Interface"
discussion: |
  Installation of configuration profiles through the user interface _MUST_ be disabled and only be permitted through an authorized MDM server.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowUIConfigurationProfileInstallation').js
  EOS
result:
  string: "false"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91775-7
  cci:
    - N/A   
  800-53r5:
    - CM-5
  800-171r2:
    - 3.4.5
  cis:
    benchmark:
      - N/A
    controls v8:
      - N/A
macOS:
  - "13.0"
tags:
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high
  - 800-171
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowUIConfigurationProfileInstallation: false