id: os_sshd_client_alive_interval_configure
title: "Configure SSHD ClientAliveInterval option set to $ODV"
discussion: |
  If SSHD is enabled then it _MUST_ be configured with an Active Client Alive Maximum Count set to $ODV. 
  
  Setting the Active Client Alive Maximum Count to $ODV (seconds) will log users out after an organizational defined interval of inactivity.

  NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/sbin/sshd -T | /usr/bin/awk '/clientaliveinterval/{print $2}'
result:
  integer: $ODV
fix: |
  [source,bash]
  ----
  include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

  if [[ -z $include_dir ]]; then
    /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
  fi

  echo "clientaliveinterval $ODV" >> "${include_dir}01-mscp-sshd.conf"

  for file in $(ls ${include_dir}); do
    if [[ "$file" == "100-macos.conf" ]]; then
        continue
    fi
    if [[ "$file" == "01-mscp-sshd.conf" ]]; then
        break
    fi
    /bin/mv ${include_dir}${file} ${include_dir}20-${file}
  done
  ----
references:
  cce:
    - CCE-91887-0
  cci: 
    - N/A
  800-53r5:
    - SC-10
    - AC-12
  800-53r4: 
    - SC-10
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.13.9
macOS:
  - "13.0"
odv:
  hint: "Number of seconds."
  recommended: 900
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171
  - cnssi-1253
severity: "medium"
mobileconfig: false
mobileconfig_info: