id: icloud_appleid_system_settings_disable
title: "Disable the System Setting for Apple ID"
discussion: |
  The system setting for Apple ID _MUST_ be disabled.

  Disabling the system setting prevents login to Apple ID and iCloud. 
check: |
  /usr/bin/profiles show -output stdout-xml | /usr/bin/xmllint --xpath '//key[text()="DisabledSystemSettings"]/following-sibling::*[1]' - | /usr/bin/grep -c com.apple.systempreferences.AppleIDSettings
result:
  integer: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91939-9
  cci: 
    - N/A
  800-53r5:
    - AC-20
    - AC-20(1)
    - CM-7
    - CM-7(1)
  800-53r4: 
    - CM-7
    - CM-7(1)
    - AC-20
    - AC-20(1)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.20
    - 3.4.6
  cis:
    benchmark:
      - N/A
    controls v8:
      - 4.1
      - 4.8
macOS:
  - "13.0"
tags:
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171 
  - cnssi-1253
  - cisv8
severity: "high"
mobileconfig: true
mobileconfig_info:
  com.apple.systempreferences:
    DisabledSystemSettings: 
      - com.apple.systempreferences.AppleIDSettings
