id: audit_retention_configure
title: "Configure Audit Retention to $ODV"
discussion: |
  The audit service _MUST_ be configured to require records be kept for a organizational defined value before deletion, unless the system uses a central audit record storage facility. 
  
  When "expire-after" is set to "$ODV", the audit service will not delete audit logs until the log data criteria is met.
check: |
  /usr/bin/awk -F: '/expire-after/{print $2}' /etc/security/audit_control
result:
  string: $ODV
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/^expire-after.*/expire-after:$ODV/' /etc/security/audit_control; /usr/sbin/audit -s
  ----
references:
  cce:
    - CCE-91731-0
  cci:
    - N/A
  800-53r5:
    - AU-11
    - AU-4
  800-53r4:
    - AU-4
    - AU-11
  srg:
    - N/A
  disa_stig:
    - N/A
  cis:
    benchmark:
      - 3.4 (level 1)
    controls v8:
      - 8.1
      - 8.3
macOS:
  - "13.0"
odv:
  hint: "See man audit_control for possible values."
  recommended: 7d
  cis_lvl1: 60d OR 5G
  cis_lvl2: 60d OR 5G
tags:
  - 800-53r5_privacy 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: "medium"
mobileconfig: false
mobileconfig_info: