id: audit_flags_fr_configure
title: "Configure System to Audit All Failed Read Actions on the System"
discussion: |
  The audit system _MUST_ be configured to record enforcement actions of access restrictions, including failed file read (-fr) attempts. 

  Enforcement actions are the methods or mechanisms used to prevent unauthorized access and/or changes to configuration settings. One common and effective enforcement action method is using access restrictions (e.g., denying access to a file by applying file permissions). 

  This configuration ensures that audit lists include events in which enforcement actions prevent attempts to read a file. 

  Without auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.
check: |
  /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\-fr'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -qE "^flags.*-fr" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,-fr/' /etc/security/audit_control;/usr/sbin/audit -s
  ----
references:
  cce:
    - CCE-91722-9
  cci:
    - N/A
  800-53r5:
    - AC-2(12)
    - AU-12
    - AU-2
    - AU-9
    - CM-5(1)
    - MA-4(1)
  800-53r4: 
    - AU-2  
    - AU-12
    - AU-9
    - CM-5(1)
    - MA-4(1)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.3.1
    - 3.3.2
    - 3.3.8
  cis:
    benchmark:
      - 3.2 (level 2)
    controls v8:
      - 3.14
      - 8.2
      - 8.5    
macOS:
  - "13.0"
tags:
  - 800-53r5_privacy 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-171 
  - cnssi-1253
  - cis_lvl2
  - cisv8
severity: "medium"
mobileconfig: false
mobileconfig_info: