id: audit_acls_files_configure
title: "Configure Audit Log Files to Not Contain Access Control Lists"
discussion: |
  The audit log files _MUST_ not contain access control lists (ACLs).
  
  This rule ensures that audit information and audit files are configured to be readable and writable only by system administrators, thereby preventing unauthorized access, modification, and deletion of files.
check: |
  /bin/ls -le $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}') | /usr/bin/awk '{print $1}' | /usr/bin/grep -c ":"
result: 
  integer: 0
fix: |
  [source,bash]
  ----
  /bin/chmod -RN $(/usr/bin/awk -F: '/^dir/{print $2}' /etc/security/audit_control)
  ----
references:
  cce:
    - CCE-91701-3
  cci:
    - N/A
  800-53r5:
    - AU-9
  800-53r4:
    - AU-9
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.3.8
  cis:
    benchmark:
      - 3.5 (level 1)
    controls v8:
      - 3.3
macOS:
  - "13.0"
tags:
  - 800-53r5_low 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-171 
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: "medium"
mobileconfig: false
mobileconfig_info:
